### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#83]
* [x] Confirm packages look correct in Unpkg
* [x] Confirm everything in npm's Readme looks good
* [x] Test installing from npm and building a simple example works (90% done)
* [x] Decide if we should expose `WasmFs` on `Wasi` object
* [x] Allow Wapm Query to work anywhere
* [x] Fix Travis / CI (originally #55 )
* [x] Open Source this repo
* [x] Publish Article
* [x] Tweet the tweets
* [x] Write https://github.com/denoland/deno/issues/3005

**Comment by torch2424** [comment]
Launched! 🎉 😄
